// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

type NavigationBar struct {
	Disabled bool
	Home     bool
	Active   string
}

func Navigation(navbar NavigationBar) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"text-gray-400 bg-gray-900 body-font\"><div class=\"container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center\"><a href=\"/\" class=\"flex title-font font-medium items-center text-white mb-4 md:mb-0\"><span class=\"ml-3 text-xl\">GoGoG</span></a><nav class=\"md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-700 flex flex-wrap items-center text-base justify-center\"><a href=\"/accounts\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if navbar.Active == "accounts" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 hover:text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Accounts</a> <a href=\"/games\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if navbar.Active == "games" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 hover:text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Games</a> <a href=\"/backups\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if navbar.Active == "backups" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 hover:text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Backups</a> <a href=\"/downloads\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if navbar.Active == "downloads" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" class=\"mr-5 hover:text-white\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">Downloads</a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
