// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

// OnboardingPage is the page to upload cookies from Gog directly
// TODO @droman: I should add a documentation on exactly how to do it manually OR to use the cli `login` that leverage chronium
func PageOnboarding() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto\"><form action=\"/api/v1/cookies\" id=\"cookies\" class=\"dropzone\" method=\"post\" enctype=\"multipart/form-data\"><div class=\"fallback\"><input name=\"cookies\" type=\"file\"></div></form></div><script>\n\t\t\tdocument.addEventListener(\"DOMContentLoaded\", function() {\n\t\t\t\tlet myDropzone = document.querySelector(\"#cookies\").dropzone;\n\t\t\t\tmyDropzone.on(\"addedfile\", function(file) {\n\t\t\t\t\tif (file.type !== \"application/json\") {\n\t\t\t\t\t\tmyDropzone.removeFile(file);\n\t\t\t\t\t\talert(\"file as to be a json\")\n\t\t\t\t\t\treturn\n\t\t\t\t\t}\n\t\t\t\t\tif (file.size > 1000000) {\n\t\t\t\t\t\tmyDropzone.removeFile(file);\n\t\t\t\t\t\talert(\"file is too big\")\n\t\t\t\t\t\treturn\n\t\t\t\t\t}\n\t\t\t\t\tif (!file.name.endsWith(\".json\")) {\n\t\t\t\t\t\tmyDropzone.removeFile(file);\n\t\t\t\t\t\talert(\"file has to end with .json\")\n\t\t\t\t\t\treturn\n\t\t\t\t\t}\n\t\t\t\t\tconsole.log(file);\n\t\t\t\t});\n\t\t\t\tmyDropzone.on(\"success\", function(file, response) {\n\t\t\t\t\tconsole.log(response);\n\t\t\t\t\twindow.location.href = \"/accounts\";\n\t\t\t\t});\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = BasePage(
			"Gogogo",
			NavigationBar{
				Home: true,
			},
		).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
